# Generated by Django 2.2 on 2020-06-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='expity_date',
            new_name='expiry_date',
        ),
        migrations.AddField(
            model_name='institute',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='institute_user', to='webapp.BaseUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to='webapp.BaseUser'),
            preserve_default=False,
        ),
    ]
