# Generated by Django 2.2 on 2020-06-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200613_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_student', to='webapp.Student'),
        ),
    ]
